*.sym = $!/sym;$!;C:\XDS\bin/../sym/x86
*.tem = $!;C:\XDS\bin
*.lib = $!;C:\XDS\bin/../lib/x86
*.prj = $!
*.def = $!/def; $!
*.mod = $!/src; $!
*.ob2 = $!/src; $!
*.obj = $!/obj
*.lnk = $!/obj
*.res = $!
